service: jobcan-tools
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, "dev"}
  region: ap-northeast-1
  deploymentBucket:
    name: ${file(deployment/serverless.${opt:stage}.yml):deploy.bucket-name}
  timeout: 29
  role: ${file(deployment/serverless.${opt:stage}.yml):iam-role.api}

functions:
  api:
    handler: app/main.handler
    events:
      - http:
          path: /
          method: Any
          cors: true
