on:
  workflow_call:
    inputs:
      role-to-assume:
        description: OIDCで使用するrole
        required: true
        type: string
      stage:
        description: デプロイ環境名
        required: true
        type: string
      sha-hash:
        description: gitのハッシュ値
        required: true
        type: string
      func-dir:
        description: デプロイする関数のディレクトリ
        required: true
        type: string
jobs:
  build:
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: ap-northeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          SHORT_GIT_HASH: ${{ inputs.sha-hash }}
        run: |
          cd ${{ inputs.func-dir }}
          ECR_REPOSITORY_NAME=jobcan-tools-api-${{ inputs.stage }}
          ECR_REPOSITORY=$ECR_REGISTRY/$ECR_REPOSITORY_NAME
          docker build -t $ECR_REPOSITORY:$SHORT_GIT_HASH -f Dockerfile .
          docker push $ECR_REPOSITORY:$SHORT_GIT_HASH
