on:
  workflow_call:
    inputs:
      role-to-assume:
        description: OIDCで使用するrole
        required: true
        type: string
      stage:
        description: デプロイ環境名
        required: true
        type: string
      sha-hash:
        description: Gitの短縮ハッシュ
        required: true
        type: string
jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: ap-northeast-1
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          npm install serverless@3.4.0
      - name: Deploy Serverless framework
        env:
          SHORT_GIT_HASH: ${{ inputs.sha-hash }}
        run: |
          npx sls deploy --stage ${{ inputs.stage }}
