on:
  workflow_call:
    inputs:
      role-to-assume:
        description: OIDCで使用するrole
        required: true
        type: string
      stage:
        description: デプロイ環境名
        required: true
        type: string
jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Get short SHA
        id: vars
        run: |
          echo "sha_short=$(echo ${GITHUB_SHA} | cut -c1-7)" >> "$GITHUB_OUTPUT"
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: ap-northeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          SHORT_GIT_HASH: ${{ steps.vars.outputs.sha_short }}
        run: |
          cd functions/api
          ECR_REPOSITORY_NAME=jobcan-tools-api-${{ inputs.stage }}
          ECR_REPOSITORY=$ECR_REGISTRY/$ECR_REPOSITORY_NAME
          docker build -t $ECR_REPOSITORY:$SHORT_GIT_HASH -f Dockerfile .
          docker push $ECR_REPOSITORY:$SHORT_GIT_HASH
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          npm install serverless@3.38.0
      - name: Deploy Serverless framework
        env:
          SHORT_GIT_HASH: ${{ steps.vars.outputs.sha_short }}
        run: |
          npx sls deploy --stage ${{ inputs.stage }}
