name: deploy-dev
on:
  push:
    branches:
      - deployment/develop
jobs:
  apply:
    uses: ./.github/workflows/_apply.yml
    with:
      stage: dev
      role-to-assume: arn:aws:iam::105785188161:role/oidc-github-actions-role
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      stage: dev
      role-to-assume: arn:aws:iam::105785188161:role/oidc-github-actions-role
