name: deploy-dev
on:
  push:
    branches:
      - deployment/develop
jobs:
  create_hash:
    runs-on: ubuntu-latest
    steps:
      - name: Get short SHA
        id: vars
        run: |
          echo "sha_short=$(echo ${GITHUB_SHA} | cut -c1-7)" >> "$GITHUB_OUTPUT"
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
  apply:
    uses: ./.github/workflows/_apply.yml
    with:
      stage: dev
      role-to-assume: arn:aws:iam::105785188161:role/oidc-github-actions-role
  build-api:
    needs: create_hash
    uses: ./.github/workflows/_build.yml
    with:
      stage: dev
      sha-hash: ${{ needs.create_hash.outputs.sha_short }}
      role-to-assume: arn:aws:iam::105785188161:role/oidc-github-actions-role
      func-dir: functions/api
  build-scraping:
    needs: create_hash
    uses: ./.github/workflows/_build.yml
    with:
      stage: dev
      sha-hash: ${{ needs.create_hash.outputs.sha_short }}
      role-to-assume: arn:aws:iam::105785188161:role/oidc-github-actions-role
      func-dir: functions/scraping-lambda
  deploy:
    needs: [create_hash, build-api, build-scraping]
    uses: ./.github/workflows/_deploy.yml
    with:
      stage: dev
      sha-hash: ${{ needs.create_hash.outputs.sha_short }}
      role-to-assume: arn:aws:iam::105785188161:role/oidc-github-actions-role
